# -*- coding: utf-8 -*-
"""Programming Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xEG7dyhP8SPBsOJqM2DdpDdpWZpT467E
"""

import numpy as np
np.random.seed(123)
random_int = np.random.randint(1, high=100, size=(20, 5))
#random_int

"""## Qn 1) What is the average value of the first 5 rows ( 2 decimal place) ?"""

random_int.mean(axis=1).round(2)[:5]

"""## Qn 2) What is the average value of the second element in each of the list (2 decimal places)? """

random_int.mean(axis=0).round(2)[1]

import pandas as pd    
data = pd.read_html("https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/")
mtcars_df = data[0]

"""## Qn 3) Get the name of the car(s) with highest power to displacement ratio"""

mtcars_df['ratio_power_displacement'] = mtcars_df['hp'] / mtcars_df['disp']
mtcars_df.sort_values('ratio_power_displacement', ascending=False)['model']

"""## Qn 4) How many cars have 4 cylinder and 4 gears?"""

mtcars_df[(mtcars_df['cyl'] == 4) & (mtcars_df['gear'] == 4)].shape[0]

"""## Q5) Write a python program to count the number occurrences of all vowels present in a string."""

def count_vowels(string):
  vowel_list = ['a', 'e', 'i', 'o', 'u']
  return sum([1 if x in vowel_list else 0 for x in string.lower()])

count_vowels("AccelerateAI - Learning Circle")